### ISSUE TITLE
Is english available?

### ISSUE THREAD

**Issue by zilveer** [alexander171294/phpoker#1]
Hello, is english available for instructions?

**Comment by alexander171294** [comment]
noup, sorry, i only speak spanish, but in the future...  who knows

**Comment by zilveer** [comment]
Ok. I would be glad if you could give instructions of i Can install this script :)

**Comment by alexander171294** [comment]
This script is only a test of PHPSocketMaster, srry :(, not need install, you start server (php cli) and copy client on your webserver in localhost, and start the client.

This script work with server-client
