### ISSUE TITLE
db

### ISSUE THREAD

**Issue by chuktuga** [alexander171294/phpoker#2]
have SQL DB ??

**Comment by alexander171294** [comment]
Srry but, this mini project, is for test websockets and my php Socket Class, the data is saved in runtime, and isn't persistent, the server start with php CLI (go to cmd or terminal and execute php /server/server.php), before configure all files.
Finally go to client folder and open that in your browse, if is configured correctly, each opened client connect to server started and represent one player.

but this is only a test, as this proyect isn't use multi-thread si a bad idea implement in a production enviorment.

Thanks for your comment, and sorry for the delay to response xD
